version: '3.9'
services:
  parser:
    container_name: parser-main
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 9117:9117
    volumes:
      - ./.docker/init.conf:/DockerOutput/init.conf:z